### ISSUE TITLE
bl_appearance issue

### ISSUE THREAD

**Issue by Pighi** [Byte-Labs-Studio/bl_appearance#23]
![image_2024-08-20_002202020](https://github.com/user-attachments/assets/cfa05697-3eff-487e-bfa4-128f886c1c95)
character is not coming with selected model after spawn . diffrenent ped appears. in console there is a warning that no data for setpedhaircolors

**Comment by DevX32** [comment]
@Pighi are u running qb-clothing and bL_appearance ??

**Comment by Pighi** [comment]
i tried bl appearance without qb- clothing but same warning no data for setpedhaircolors and my character was invisible

**Comment by DevX32** [comment]
@Pighi thats just an warning ignore it but char should show

**Comment by DevX32** [comment]
@Pighi can u join discord? so i can assist you there

**Comment by Pighi** [comment]
yes i will

**Comment by Pighi** [comment]
i will talk to you in discord later

**Comment by DevX32** [comment]
@Pighi ok for now closing the issue u can tag me devx in discord
