### ISSUE TITLE
Command appears invalid out of zone when I click on "E"

### ISSUE THREAD

**Issue by RedTugaa** [Byte-Labs-Studio/bl_appearance#8]
![image](https://github.com/user-attachments/assets/e9600b6e-93bd-4e7d-8da2-64a18f2a9ca8)

If I click on E anywhere on the map this command appears invalid.

He's not keeping his tattoos either

**Comment by paruthepro** [comment]
Need more repro steps for the tattoos bug.

**Comment by DevX32** [comment]
which fw? @RedTugaa

**Comment by RedTugaa** [comment]
Last ESX

**Comment by RedTugaa** [comment]
the command is +openAppearance,  when I click on E it triggers the openAppearance command everywhere, why... I don't have anything on the server that is triggering the openAppearance command

**Comment by RedTugaa** [comment]
Just Change data/zones.lua from this:

```
RegisterCommand('+openAppearance', function()
    if not currentZone then return end
    TriggerEvent('bl_sprites:client:useZone', currentZone)
end, false)

RegisterKeyMapping('+openAppearance', 'Open Appearance', 'keyboard', key)
```

To this:

```
RegisterCommand('openAppearance', function()
    if not currentZone then return end
    TriggerEvent('bl_sprites:client:useZone', currentZone)
end, false)

RegisterKeyMapping('openAppearance', 'Open Appearance', 'keyboard', key)
```
